// +build swagon

package main

// docs is generated by Swag CLI, you have to import it.
// this is turned off by default as we don't want swag API imported on production
// in order to use this, compile the program with:
// go build -tags=swagon
import _ "github.com/henvic/galaxy/docs"
