// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-04-08 18:33:06.098907 -0300 -03 m=+0.042464752

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/": {
            "get": {
                "description": "Healthcheck endpoint",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "galaxy"
                ],
                "summary": "Home",
                "operationId": "home-galaxy",
                "responses": {
                    "200": {}
                }
            }
        },
        "/sectors/{sector_id}/dns": {
            "post": {
                "description": "Get a DNS location of a sector of the galaxy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "galaxy"
                ],
                "summary": "Show a DNS location",
                "operationId": "dns-sector-galaxy",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Sector ID",
                        "name": "sector_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.DNSResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "406": {
                        "description": "Not Acceptable",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server.DNSResponse": {
            "type": "object",
            "properties": {
                "loc": {
                    "type": "number",
                    "example": 27372.229
                }
            }
        },
        "server.ErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "string",
                    "example": "reference not found"
                },
                "message": {
                    "type": "string",
                    "example": "Not Found"
                },
                "status": {
                    "type": "integer",
                    "example": 404
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
